//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.21 at 11:54:12 Õ EEST 
//


package telecom.sudparis.eu.paas.core.server.xml.manifest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paas_environmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paas_environmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paas_environment_template" type="{}paas_environment_templateType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operatingsystem" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="programminglang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="template" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paas_environmentType", propOrder = {
    "paasEnvironmentTemplate"
})
public class PaasEnvironmentType {

    @XmlElement(name = "paas_environment_template", required = true)
    protected PaasEnvironmentTemplateType paasEnvironmentTemplate;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String operatingsystem;
    @XmlAttribute
    protected String programminglang;
    @XmlAttribute
    protected String template;

    /**
     * Gets the value of the paasEnvironmentTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link PaasEnvironmentTemplateType }
     *     
     */
    public PaasEnvironmentTemplateType getPaasEnvironmentTemplate() {
        return paasEnvironmentTemplate;
    }

    /**
     * Sets the value of the paasEnvironmentTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaasEnvironmentTemplateType }
     *     
     */
    public void setPaasEnvironmentTemplate(PaasEnvironmentTemplateType value) {
        this.paasEnvironmentTemplate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the operatingsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingsystem() {
        return operatingsystem;
    }

    /**
     * Sets the value of the operatingsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
   public void setOperatingsystem(String value) {
        this.operatingsystem = value;
    }

    /**
     * Gets the value of the programminglang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramminglang() {
        return programminglang;
    }

    /**
     * Sets the value of the programminglang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
   /* public void setProgramminglang(String value) {
        this.programminglang = value;
    }*/

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

}
