//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 01:34:22 ã EEST 
//


package telecom.sudparis.eu.paas.core.server.xml.application;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deployableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deployableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="deployableDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deployableId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deployableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deployableType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deployableType")
public class DeployableType {

    @XmlAttribute
    protected String deployableDirectory;
    @XmlAttribute
    protected String deployableId;
    @XmlAttribute
    protected String deployableName;
    @XmlAttribute
    protected String deployableType;

    /**
     * Gets the value of the deployableDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployableDirectory() {
        return deployableDirectory;
    }

    /**
     * Sets the value of the deployableDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployableDirectory(String value) {
        this.deployableDirectory = value;
    }

    /**
     * Gets the value of the deployableId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployableId() {
        return deployableId;
    }

    /**
     * Sets the value of the deployableId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployableId(String value) {
        this.deployableId = value;
    }

    /**
     * Gets the value of the deployableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployableName() {
        return deployableName;
    }

    /**
     * Sets the value of the deployableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployableName(String value) {
        this.deployableName = value;
    }

    /**
     * Gets the value of the deployableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployableType() {
        return deployableType;
    }

    /**
     * Sets the value of the deployableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployableType(String value) {
        this.deployableType = value;
    }

}
