//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.26 at 10:10:09 AM CET 
//


package telecom.sudparis.eu.paas.core.server.xml.manifest;

import java.math.BigDecimal;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paas_application_versionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paas_application_versionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paas_application_deployable" type="{}paas_application_deployableType"/>
 *         &lt;element name="paas_application_version_instance" type="{}paas_application_version_instanceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paas_application_versionType", propOrder = {
    "paasApplicationDeployable",
    "paasApplicationVersionInstance"
})
public class PaasApplicationVersionType {

    @XmlElement(name = "paas_application_deployable", required = true)
    protected PaasApplicationDeployableType paasApplicationDeployable;
    @XmlElement(name = "paas_application_version_instance", required = true)
    protected List<PaasApplicationVersionInstanceType> paasApplicationVersionInstance;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected BigDecimal label;

    /**
     * Gets the value of the paasApplicationDeployable property.
     * 
     * @return
     *     possible object is
     *     {@link PaasApplicationDeployableType }
     *     
     */
    public PaasApplicationDeployableType getPaasApplicationDeployable() {
        return paasApplicationDeployable;
    }

    /**
     * Sets the value of the paasApplicationDeployable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaasApplicationDeployableType }
     *     
     */
    public void setPaasApplicationDeployable(PaasApplicationDeployableType value) {
        this.paasApplicationDeployable = value;
    }

    /**
     * Gets the value of the paasApplicationVersionInstance property.
     * 
     * @return
     *     possible object is
     *     {@link PaasApplicationVersionInstanceType }
     *     
     */
    public List<PaasApplicationVersionInstanceType> getPaasApplicationVersionInstance() {
        return paasApplicationVersionInstance;
    }

    /**
     * Sets the value of the paasApplicationVersionInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaasApplicationVersionInstanceType }
     *     
     */
    public void setPaasApplicationVersionInstance(List<PaasApplicationVersionInstanceType> value) {
        this.paasApplicationVersionInstance = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLabel(BigDecimal value) {
        this.label = value;
    }

}
