//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.22 at 12:42:01 ã EEST 
//


package telecom.sudparis.eu.paas.core.server.xml.environment.list;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the telecom.sudparis.eu.paas.core.server.xml.environment.list package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Environments_QNAME = new QName("", "environments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: telecom.sudparis.eu.paas.core.server.xml.environment.list
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvironmentsType }
     * 
     */
    public EnvironmentsType createEnvironmentsType() {
        return new EnvironmentsType();
    }

    /**
     * Create an instance of {@link SimpleEnvironmentType }
     * 
     */
    public SimpleEnvironmentType createSimpleEnvironmentType() {
        return new SimpleEnvironmentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvironmentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "environments")
    public JAXBElement<EnvironmentsType> createEnvironments(EnvironmentsType value) {
        return new JAXBElement<EnvironmentsType>(_Environments_QNAME, EnvironmentsType.class, null, value);
    }

}
